# This file was generated by GoReleaser. DO NOT EDIT.
class Hydra < Formula
  desc ""
  homepage "https://www.ory.sh"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ory/hydra/releases/download/v1.1.0/hydra_1.1.0_macOS_64-bit.tar.gz"
    sha256 "c1c7095da41319a400192a674674114805c44fe5ba2ab83818a618637b49bed4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v1.1.0/hydra_1.1.0_Linux_64-bit.tar.gz"
      sha256 "0530c30a80fffab0e9a682087469edfe0e622aedc217116faf72c6bcebea150e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ory/hydra/releases/download/v1.1.0/hydra_1.1.0_Linux_arm64.tar.gz"
        sha256 "7dd9dc1620050f62c367c007f9089de0038cf5962ce10c9afe085da966ff4d68"
      else
        url "https://github.com/ory/hydra/releases/download/v1.1.0/hydra_1.1.0_Linux_armv6.tar.gz"
        sha256 "e2d42011d6817a59705a996c982505cc4a9d93892f9e281a9b5b064cc13feda8"
      end
    end
  end

  def install
    bin.install "hydra"
  end
end
