# This file was generated by GoReleaser. DO NOT EDIT.
class Hydra < Formula
  desc ""
  homepage "https://www.ory.sh"
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ory/hydra/releases/download/v1.0.5/hydra_1.0.5_macOS_64-bit.tar.gz"
    sha256 "dc08901c3fa158db99b3fbe9dbb8d4127ea4d7baec477dbdd6f0c43d8595a2bc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v1.0.5/hydra_1.0.5_Linux_64-bit.tar.gz"
      sha256 "4832945ab0e397e4c429094124bc6aca2577f92017503c0d47b9d7934e38308c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ory/hydra/releases/download/v1.0.5/hydra_1.0.5_Linux_arm64.tar.gz"
        sha256 "4466819678753616b65ab2c8d66b2e49d44c22038c66ff2c1794531411f176d3"
      else
        url "https://github.com/ory/hydra/releases/download/v1.0.5/hydra_1.0.5_Linux_armv6.tar.gz"
        sha256 "b47301a21c221ef828900cdb1026aab82b39076d791f90364f73c8524ca72efc"
      end
    end
  end

  def install
    bin.install "hydra"
  end
end
