# This file was generated by GoReleaser. DO NOT EDIT.
class Hydra < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/hydra/releases/download/v1.0.0-rc.9+oryOS.10/hydra_1.0.0-rc.9+oryOS.10_macOS_64-bit.tar.gz"
  version "1.0.0-rc.9+oryOS.10"
  sha256 "c49088dec4c08ec9fc1698e1a6a54e52451acf9e043b61fe9a06f03fc410e774"

  def install
    bin.install "hydra"
  end
end
